# Generated by Django 5.0.1 on 2024-06-06 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apcitizenapp', '0003_mlapolling_mppolling'),
    ]

    operations = [
        migrations.DeleteModel(
            name='mlapolling',
        ),
        migrations.DeleteModel(
            name='mppolling',
        ),
    ]
