# Generated by Django 5.0.1 on 2024-06-06 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apcitizenapp', '0004_delete_mlapolling_delete_mppolling'),
    ]

    operations = [
        migrations.CreateModel(
            name='mlapolling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.IntegerField(unique=True)),
                ('MLA_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='mppolling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.IntegerField(unique=True)),
                ('MP_name', models.CharField(max_length=50)),
            ],
        ),
    ]
